from django import forms

class UserForm(forms.Form):
    name = forms.CharField(label='name')
    dob_year = forms.CharField(label='dob_year')
    dob_month = forms.CharField(label='dob_month')
    dob_day = forms.CharField(label='dob_day')
    age = forms.CharField(label='age')
    goalAge = forms.CharField(label='goalAge')
    gender = forms.CharField(label='gender')
    salary = forms.CharField(label='salary')
    bonus = forms.CharField(label='bonus')
    cab = forms.CharField(label='cab')
    mab = forms.CharField(label='mab')
    sab = forms.CharField(label='sab')
    ahdb = forms.CharField(label='ahdb')
    houseAmount = forms.CharField(label='houseAmount')
    dpp = forms.CharField(label='dpp')
    yearsToGo = forms.CharField(label='yearsToGo')
    hdb = forms.ChoiceField(label='hdb')
    investment = forms.CharField(label='investment')
    save = forms.ChoiceField(label='save')
    plan = forms.ChoiceField(label='plan')
    sum = forms.CharField(label='sum')
    premiums = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, label='premiums')
